### ISSUE TITLE
Error when trying to import LSGConverter

### ISSUE THREAD

**Issue by RibinMathewChalumattu** [ccdv-ai/convert_checkpoint_to_lsg#4]
Hi,

I get the following error message when trying to convert a model with the lsg_converter package. Do you know what the issue might be? My transformers version is 4.22.2 :
```
Traceback (most recent call last):
  File "/home/cribin/Documents/MDS/mds-project-repo/mds-project/mds_model/lsg_converter/convert_mbart_to_lsg.py", line 1, in <module>
    from lsg_converter import LSGConverter
  File "/home/cribin/Documents/MDS/mds-project-repo/mds-project/venv/lib/python3.8/site-packages/lsg_converter/__init__.py", line 1, in <module>
    from .converter import *
  File "/home/cribin/Documents/MDS/mds-project-repo/mds-project/venv/lib/python3.8/site-packages/lsg_converter/converter.py", line 9, in <module>
    from .camembert.convert_camembert_checkpoint import *
  File "/home/cribin/Documents/MDS/mds-project-repo/mds-project/venv/lib/python3.8/site-packages/lsg_converter/camembert/convert_camembert_checkpoint.py", line 1, in <module>
    from .modeling_lsg_camembert import *
  File "/home/cribin/Documents/MDS/mds-project-repo/mds-project/venv/lib/python3.8/site-packages/lsg_converter/camembert/modeling_lsg_camembert.py", line 394, in <module>
    class LSGCamembertEmbeddings(CamembertEmbeddings):
NameError: name 'CamembertEmbeddings' is not defined
```

**Comment by ccdv-ai** [comment]
hi @RibinMTC 

This is likely an issue with the transformers version. CamemBERT was fully inherited from RoBERTa in the past, they made the change in 4.23.0. 

Can you try with a newer transformers version?
I will check the issue and change the required version.

**Comment by RibinMathewChalumattu** [comment]
Thanks, upgrading to version 4.23.0 fixed the problem.

Best,
Ribin

**Comment by toniopelo** [comment]
Just for reference if anybody end up here like me, the last versions that worked for me for camembert was
`lsg-converter==0.1.8 transformers==4.35.2` (I didn't search too much though)
After that I got the `name 'AlbertEmbeddings' is not defined` error
